# Generated by Django 4.1.4 on 2022-12-26 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colors', '0001_initial'),
        ('adopts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenePool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('type', models.CharField(choices=[('basic', 'Basic'), ('multi', 'Multi')], max_length=10)),
                ('genes_count', models.IntegerField(default=0)),
                ('genes_weight_total', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_deleted', models.DateTimeField(null=True)),
                ('adopt', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='adopts.adopt')),
                ('color_pool', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='colors.colorpool')),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('has_lines', models.BooleanField(default=False)),
                ('weight', models.IntegerField(default=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_deleted', models.DateTimeField(null=True)),
                ('color_pool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='colors.colorpool')),
                ('gene_pool', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='genes.genepool')),
            ],
        ),
    ]
