# Generated by Django 4.1.4 on 2022-12-27 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adopts', '0002_alter_adopt_mods'),
        ('genes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genepool',
            name='sort',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gene',
            name='gene_pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='genes', to='genes.genepool'),
        ),
        migrations.AlterField(
            model_name='genepool',
            name='adopt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='gene_pools', to='adopts.adopt'),
        ),
    ]
