# Generated by Django 4.1.4 on 2022-12-27 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0003_genelayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genelayer',
            name='gene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='gene_layers', to='genes.gene'),
        ),
    ]
