# Generated by Django 4.1.4 on 2022-12-27 16:50

from django.db import migrations, models
import django.db.models.deletion
import genes.models


class Migration(migrations.Migration):

    dependencies = [
        ('adopts', '0005_alter_adoptlayer_image_alter_adoptlayer_type'),
        ('genes', '0004_alter_genelayer_gene'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='adopt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='genes', to='adopts.adopt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genelayer',
            name='adopt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='gene_layers', to='adopts.adopt'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genelayer',
            name='image',
            field=models.ImageField(null=True, upload_to=genes.models.gene_layer_to_image_path),
        ),
    ]
