# Generated by Django 4.1.4 on 2022-12-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0005_gene_adopt_genelayer_adopt_alter_genelayer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genelayer',
            name='type',
            field=models.CharField(choices=[('static_over', 'Static on top of adopt'), ('shading_over', 'Shading on top of adopt'), ('highlights_over', 'Highlights on top of adopt'), ('color_over', 'Color pool on top of adopt'), ('static_on', 'Static on base'), ('color_on', 'Color on base'), ('static_under', 'Static under adopt'), ('shading_under', 'Shading under adopt'), ('highlights_under', 'Highlights under adopt'), ('color_under', 'Color under adopt')], max_length=20),
        ),
    ]
