# Generated by Django 4.1.4 on 2023-01-01 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0006_alter_genelayer_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genelayer',
            options={'ordering': ('-sort',)},
        ),
    ]
