# Generated by Django 4.1.4 on 2023-01-01 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0007_alter_genelayer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='genelayer',
            name='required_gene_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='dependent_gene_layers', to='genes.gene'),
        ),
    ]
