# Generated by Django 4.1.4 on 2023-01-01 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0008_genelayer_required_gene_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genelayer',
            old_name='required_gene_id',
            new_name='required_gene',
        ),
    ]
