# Generated by Django 4.1.4 on 2023-01-03 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0010_gene_has_color_gene_slug_genepool_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='genelayer',
            name='required_gene_pool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='dependent_gene_layers', to='genes.genepool'),
        ),
    ]
