# Generated by Django 4.1.4 on 2022-12-26 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_user_id', models.IntegerField(db_index=True, null=True)),
                ('discord_user_username', models.CharField(max_length=32)),
                ('discord_user_discriminator', models.CharField(max_length=4)),
                ('discord_user_avatar', models.CharField(max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
