services:
  web:
    build: 
      context: .
      dockerfile: ./docker/web/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000 --insecure
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=rngadopts
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    env_file:
      - ".env"
    depends_on:
      db:
        condition: service_healthy
        # https://stackoverflow.com/questions/35069027/docker-wait-for-postgresql-to-be-running
    networks:
      - web
      - expose
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_DB=rngadopts
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - web
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  npm:
    image: node:19.3-alpine
    volumes:
      - ./frontend:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "5173:5173"
    profiles:
      - donotstart
    env_file:
      - ".env"
  expose:
    build: ./docker/expose
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    profiles:
      - donotstart
    command: share web:8000 --server-host=${EXPOSE_SERVER_HOST:-sharedwithexpose.com} --server-port=${EXPOSE_SERVER_PORT:-443} --subdomain=${EXPOSE_SUBDOMAIN:-rngadopts} --auth=${EXPOSE_TOKEN}
    networks:
      - expose
networks:
  expose:
    driver: bridge
  web:
    driver: bridge