services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_DB=rngadopts
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - web
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=rngadopts
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    env_file:
      - ".env"
    depends_on:
      - db
    networks:
      - web
      - expose
  npm:
    image: node:19.3-alpine
    volumes:
      - ./frontend:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "5173:5173"
    profiles:
      - donotstart
    env_file:
      - ".env"
  expose:
    build: ./docker/expose
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    profiles:
      - donotstart
    command: share web:8000 --server-host=${EXPOSE_SERVER_HOST:-sharedwithexpose.com} --server-port=${EXPOSE_SERVER_PORT:-443} --subdomain=${EXPOSE_SUBDOMAIN:-rngadopts} --auth=${EXPOSE_TOKEN}
    networks:
      - expose
networks:
  expose:
    driver: bridge
  web:
    driver: bridge