# Generated by Django 4.1.4 on 2022-12-27 10:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adopts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopt',
            name='mods',
            field=models.ManyToManyField(related_name='adopts', through='adopts.AdoptMod', to=settings.AUTH_USER_MODEL),
        ),
    ]
