# Generated by Django 4.1.4 on 2022-12-27 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colors', '0002_alter_colorpool_adopt_alter_colorpool_colors'),
        ('adopts', '0002_alter_adopt_mods'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adopt',
            old_name='count',
            new_name='genes_count',
        ),
        migrations.AddField(
            model_name='adopt',
            name='layers_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adopt',
            name='logs_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='adoptlog',
            name='adopt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='adopt_logs', to='adopts.adopt'),
        ),
        migrations.AlterField(
            model_name='adoptlog',
            name='mod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='adopt_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AdoptLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('type', models.CharField(choices=[('static_over', 'Static image (eg. lines, eye whites)'), ('shading', 'Shading'), ('highlights', 'Highlights'), ('color', 'Generate all colors from color pool (eg. eye color)')], max_length=20)),
                ('sort', models.IntegerField(default=0)),
                ('adopt', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='adopt_layers', to='adopts.adopt')),
                ('color_pool', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='colors.colorpool')),
            ],
        ),
    ]
