# Generated by Django 4.1.4 on 2022-12-27 16:50

import adopts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopts', '0004_alter_adoptlayer_color_pool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptlayer',
            name='image',
            field=models.ImageField(null=True, upload_to=adopts.models.adopt_layer_to_image_path),
        ),
        migrations.AlterField(
            model_name='adoptlayer',
            name='type',
            field=models.CharField(choices=[('static', 'Static image (eg. lines, eye whites)'), ('shading', 'Shading'), ('highlights', 'Highlights'), ('color', 'Generate all colors from color pool (eg. eye color)')], max_length=20),
        ),
    ]
