# Generated by Django 4.1.4 on 2022-12-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopts', '0005_alter_adoptlayer_image_alter_adoptlayer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopt',
            name='colors_count',
            field=models.IntegerField(default=0),
        ),
    ]
