# Generated by Django 4.1.4 on 2022-12-30 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0005_gene_adopt_genelayer_adopt_alter_genelayer_image'),
        ('adopts', '0006_adopt_colors_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptlayer',
            name='color_pool',
        ),
        migrations.AddField(
            model_name='adoptlayer',
            name='gene_pool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='genes.genepool'),
        ),
        migrations.AlterField(
            model_name='adoptlayer',
            name='type',
            field=models.CharField(choices=[('static', 'Static image (eg. lines, eye whites)'), ('shading', 'Shading'), ('highlights', 'Highlights'), ('gene', 'Gene pool')], max_length=20),
        ),
    ]
