# Generated by Django 4.1.4 on 2023-01-01 01:46

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adopts', '0008_alter_adoptlayer_options_adopt_height_adopt_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopt',
            name='current_display_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='adopt',
            name='gen_caption',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='adoptlog',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adoptlog',
            name='display_id',
            field=models.IntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adoptlog',
            name='image_code',
            field=models.CharField(default='', max_length=516),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adopt',
            name='height',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(800)]),
        ),
        migrations.AlterField(
            model_name='adopt',
            name='width',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(800)]),
        ),
        migrations.AlterField(
            model_name='adoptlog',
            name='image_url',
            field=models.CharField(max_length=516),
        ),
    ]
