# Generated by Django 4.1.4 on 2023-01-03 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopts', '0010_alter_adoptlog_discord_channel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopt',
            name='date_deleted',
            field=models.DateTimeField(blank=True, null=True),
        )
    ]
