# Generated by Django 4.1.4 on 2022-12-27 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adopts', '0002_alter_adopt_mods'),
        ('colors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorpool',
            name='adopt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='color_pool', to='adopts.adopt'),
        ),
        migrations.AlterField(
            model_name='colorpool',
            name='colors',
            field=models.JSONField(default=list),
        ),
    ]
