# Generated by Django 4.1.4 on 2022-12-28 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0003_alter_colorpool_adopt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorpool',
            name='colors',
            field=models.TextField(default=''),
        ),
    ]
